### ISSUE TITLE
Python compatibility

### ISSUE THREAD

**Issue by ghost** [C-Corbin/comfy_BED#28]
Check it all still works with Python 3 (dev was in 2). If not, fix or change ReadMe.

**Comment by erikwaskiewicz** [comment]
No longer works with Python3 - error when writing to file.  
Its probably quite a small fix, but to avoid opening a can of worms, the README has been changed to say that the program only works with Python 2.    
Error message:

```Traceback (most recent call last):
  File "comfy_BED/comfy_BED.py", line 271, in <module>
    main()
  File "comfy_BED/comfy_BED.py", line 266, in main
    writeToFile(publicOrPrivate, publicOrPrivateMessage, exon_genomic_positions, file_name, now)
  File "comfy_BED/comfy_BED.py", line 201, in writeToFile
    out.writelines('#BED file generated at: ' + now.strftime("%Y-%m-%d %H:%M") + '\n')
TypeError: a bytes-like object is required, not 'str'```
